### YamlMime:ManagedReference
items:
- uid: BooklinkBE.API.Options.EnvironmentOptions
  commentId: T:BooklinkBE.API.Options.EnvironmentOptions
  id: EnvironmentOptions
  parent: BooklinkBE.API.Options
  children:
  - BooklinkBE.API.Options.EnvironmentOptions.FrontendConfirmUrl
  - BooklinkBE.API.Options.EnvironmentOptions.FrontendHostUrl
  - BooklinkBE.API.Options.EnvironmentOptions.SenderEmail
  - BooklinkBE.API.Options.EnvironmentOptions.SenderName
  langs:
  - csharp
  - vb
  name: EnvironmentOptions
  nameWithType: EnvironmentOptions
  fullName: BooklinkBE.API.Options.EnvironmentOptions
  type: Class
  source:
    remote:
      path: BooklinkBE.API/Options/EnvironmentOptions.cs
      branch: main
      repo: https://github.com/1-IT-Gymnazium/1046_Booklink_BE.git
    id: EnvironmentOptions
    path: ../../BooklinkBE.API/Options/EnvironmentOptions.cs
    startLine: 2
  assemblies:
  - BooklinkBE.API
  namespace: BooklinkBE.API.Options
  syntax:
    content: public class EnvironmentOptions
    content.vb: Public Class EnvironmentOptions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: BooklinkBE.API.Options.EnvironmentOptions.FrontendHostUrl
  commentId: P:BooklinkBE.API.Options.EnvironmentOptions.FrontendHostUrl
  id: FrontendHostUrl
  parent: BooklinkBE.API.Options.EnvironmentOptions
  langs:
  - csharp
  - vb
  name: FrontendHostUrl
  nameWithType: EnvironmentOptions.FrontendHostUrl
  fullName: BooklinkBE.API.Options.EnvironmentOptions.FrontendHostUrl
  type: Property
  source:
    remote:
      path: BooklinkBE.API/Options/EnvironmentOptions.cs
      branch: main
      repo: https://github.com/1-IT-Gymnazium/1046_Booklink_BE.git
    id: FrontendHostUrl
    path: ../../BooklinkBE.API/Options/EnvironmentOptions.cs
    startLine: 4
  assemblies:
  - BooklinkBE.API
  namespace: BooklinkBE.API.Options
  syntax:
    content: public required string FrontendHostUrl { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property FrontendHostUrl As String
  overload: BooklinkBE.API.Options.EnvironmentOptions.FrontendHostUrl*
- uid: BooklinkBE.API.Options.EnvironmentOptions.FrontendConfirmUrl
  commentId: P:BooklinkBE.API.Options.EnvironmentOptions.FrontendConfirmUrl
  id: FrontendConfirmUrl
  parent: BooklinkBE.API.Options.EnvironmentOptions
  langs:
  - csharp
  - vb
  name: FrontendConfirmUrl
  nameWithType: EnvironmentOptions.FrontendConfirmUrl
  fullName: BooklinkBE.API.Options.EnvironmentOptions.FrontendConfirmUrl
  type: Property
  source:
    remote:
      path: BooklinkBE.API/Options/EnvironmentOptions.cs
      branch: main
      repo: https://github.com/1-IT-Gymnazium/1046_Booklink_BE.git
    id: FrontendConfirmUrl
    path: ../../BooklinkBE.API/Options/EnvironmentOptions.cs
    startLine: 5
  assemblies:
  - BooklinkBE.API
  namespace: BooklinkBE.API.Options
  syntax:
    content: public required string FrontendConfirmUrl { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property FrontendConfirmUrl As String
  overload: BooklinkBE.API.Options.EnvironmentOptions.FrontendConfirmUrl*
- uid: BooklinkBE.API.Options.EnvironmentOptions.SenderEmail
  commentId: P:BooklinkBE.API.Options.EnvironmentOptions.SenderEmail
  id: SenderEmail
  parent: BooklinkBE.API.Options.EnvironmentOptions
  langs:
  - csharp
  - vb
  name: SenderEmail
  nameWithType: EnvironmentOptions.SenderEmail
  fullName: BooklinkBE.API.Options.EnvironmentOptions.SenderEmail
  type: Property
  source:
    remote:
      path: BooklinkBE.API/Options/EnvironmentOptions.cs
      branch: main
      repo: https://github.com/1-IT-Gymnazium/1046_Booklink_BE.git
    id: SenderEmail
    path: ../../BooklinkBE.API/Options/EnvironmentOptions.cs
    startLine: 6
  assemblies:
  - BooklinkBE.API
  namespace: BooklinkBE.API.Options
  syntax:
    content: public required string SenderEmail { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property SenderEmail As String
  overload: BooklinkBE.API.Options.EnvironmentOptions.SenderEmail*
- uid: BooklinkBE.API.Options.EnvironmentOptions.SenderName
  commentId: P:BooklinkBE.API.Options.EnvironmentOptions.SenderName
  id: SenderName
  parent: BooklinkBE.API.Options.EnvironmentOptions
  langs:
  - csharp
  - vb
  name: SenderName
  nameWithType: EnvironmentOptions.SenderName
  fullName: BooklinkBE.API.Options.EnvironmentOptions.SenderName
  type: Property
  source:
    remote:
      path: BooklinkBE.API/Options/EnvironmentOptions.cs
      branch: main
      repo: https://github.com/1-IT-Gymnazium/1046_Booklink_BE.git
    id: SenderName
    path: ../../BooklinkBE.API/Options/EnvironmentOptions.cs
    startLine: 7
  assemblies:
  - BooklinkBE.API
  namespace: BooklinkBE.API.Options
  syntax:
    content: public required string SenderName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property SenderName As String
  overload: BooklinkBE.API.Options.EnvironmentOptions.SenderName*
references:
- uid: BooklinkBE.API.Options
  commentId: N:BooklinkBE.API.Options
  href: BooklinkBE.html
  name: BooklinkBE.API.Options
  nameWithType: BooklinkBE.API.Options
  fullName: BooklinkBE.API.Options
  spec.csharp:
  - uid: BooklinkBE
    name: BooklinkBE
    href: BooklinkBE.html
  - name: .
  - uid: BooklinkBE.API
    name: API
    href: BooklinkBE.API.html
  - name: .
  - uid: BooklinkBE.API.Options
    name: Options
    href: BooklinkBE.API.Options.html
  spec.vb:
  - uid: BooklinkBE
    name: BooklinkBE
    href: BooklinkBE.html
  - name: .
  - uid: BooklinkBE.API
    name: API
    href: BooklinkBE.API.html
  - name: .
  - uid: BooklinkBE.API.Options
    name: Options
    href: BooklinkBE.API.Options.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: BooklinkBE.API.Options.EnvironmentOptions.FrontendHostUrl*
  commentId: Overload:BooklinkBE.API.Options.EnvironmentOptions.FrontendHostUrl
  href: BooklinkBE.API.Options.EnvironmentOptions.html#BooklinkBE_API_Options_EnvironmentOptions_FrontendHostUrl
  name: FrontendHostUrl
  nameWithType: EnvironmentOptions.FrontendHostUrl
  fullName: BooklinkBE.API.Options.EnvironmentOptions.FrontendHostUrl
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: BooklinkBE.API.Options.EnvironmentOptions.FrontendConfirmUrl*
  commentId: Overload:BooklinkBE.API.Options.EnvironmentOptions.FrontendConfirmUrl
  href: BooklinkBE.API.Options.EnvironmentOptions.html#BooklinkBE_API_Options_EnvironmentOptions_FrontendConfirmUrl
  name: FrontendConfirmUrl
  nameWithType: EnvironmentOptions.FrontendConfirmUrl
  fullName: BooklinkBE.API.Options.EnvironmentOptions.FrontendConfirmUrl
- uid: BooklinkBE.API.Options.EnvironmentOptions.SenderEmail*
  commentId: Overload:BooklinkBE.API.Options.EnvironmentOptions.SenderEmail
  href: BooklinkBE.API.Options.EnvironmentOptions.html#BooklinkBE_API_Options_EnvironmentOptions_SenderEmail
  name: SenderEmail
  nameWithType: EnvironmentOptions.SenderEmail
  fullName: BooklinkBE.API.Options.EnvironmentOptions.SenderEmail
- uid: BooklinkBE.API.Options.EnvironmentOptions.SenderName*
  commentId: Overload:BooklinkBE.API.Options.EnvironmentOptions.SenderName
  href: BooklinkBE.API.Options.EnvironmentOptions.html#BooklinkBE_API_Options_EnvironmentOptions_SenderName
  name: SenderName
  nameWithType: EnvironmentOptions.SenderName
  fullName: BooklinkBE.API.Options.EnvironmentOptions.SenderName
